### ISSUE TITLE
phyloFlash_makedb.pl failed # error code 256

### ISSUE THREAD

**Issue by DennisJakob** [HRGV/phyloFlash#106]
Hi,
I am getting a fatal error with code 256 when trying to create the reference DB. 
Everything looks fine until the bbduk.sh step.

[15:44:17] running subcommand:
/home/usr/software/bin/[/home/usr/software/bin/miniconda3]/envs/phyloflash/bin/bbduk.sh
	   ref=UniVec	overwrite=t -Xmx10g threads=40 fastawrap=0 ktrim=r
	   ow=t minlength=800 mink=11 hdist=1
	   in=./138//SILVA_SSU.noLSU.masked.fasta
	   out=./138//SILVA_SSU.noLSU.masked.trimmed.fasta
	   stats=./138//SILVA_SSU.noLSU.masked.trimmed.fasta.UniVec_contamination_stats.txt
	   2>tmp.bbduk_remove_univec.log
[15:44:25] FATAL: Tool execution failed!.
	   Error was 'No such file or directory' and return code '256'
	   Aborting.
[15:44:25] Saving log to file phyloFlash_log_on_error

The log file says it has problems finding primes.txt.gz and indeed it looks like the file is not where it is supposed to be. 
I think the script looks for it under ../envs/phyloflash/opt/bbmap-38.79-0/current/primes.txt.gz
I find it under ../envs/phyloflash/opt/bbmap-38.79-0/resources/primes.txt.gz
Any suggestions how to handle this? I tried copying it to the 'current' folder without success.

Best,
Dennis

[tmp.bbduk_remove_univec.log](https://github.com/HRGV/phyloFlash/files/4387959/tmp.bbduk_remove_univec.log)

**Comment by kbseah** [comment]
Hi Dennis,
I'm wondering why the path
`/home/usr/software/bin/[/home/usr/software/bin/miniconda3]/envs/phyloflash/bin/bbduk.sh`
has brackets `[` `]` in it. What operating system are you using?
Cheers,
Brandon

**Comment by DennisJakob** [comment]
Hi Brandon,
Your were complete right. The problem was with my conda installation. 
After setting it up it worked fine!
Thanks anyways.

Cheers,
Dennis
