### ISSUE TITLE
Error in phyloFlash_fastgFishing: Use of uninitialized value

### ISSUE THREAD

**Issue by sarah872** [HRGV/phyloFlash#111]
I wanted to run the `phyloFlash_fastgFishing.pl` script to extract cluster of contigs:

```
phyloFlash_fastgFishing.pl --fasta Aceto.contigs.fasta --fastg Aceto.assembly_graph.fastg --out Aceto_fastg --assembler spades --compare-zip Aceto.phyloFlash.tar.gz --paths $(which spades.py) --outfasta
```
But all it threw were a lot of errors `Use of uninitialized value within %edgefull in hash element at /apps/phyloflash/3.3/phyloFlash_fastgFishing.pl line 662, <$fh> line 10.`

Please see the log-file attached.

[nohup.txt](https://github.com/HRGV/phyloFlash/files/4539377/nohup.txt)

**Comment by kbseah** [comment]
Hello @sarah872 ,
The `--paths` option should point to the `<output_dir>/contigs.paths` file in the SPAdes output (see description in [SPAdes manual](http://cab.spbu.ru/files/release3.14.1/manual.html#sec3.5)), not the path to the SPAdes program. If the input assembly is the `scaffolds.fasta` file, then the `--paths` option should point to the `scaffolds.paths` file instead. Could you give that a try?

**Comment by sarah872** [comment]
Thanks for the prompt response! It works now.
