### ISSUE TITLE
Phyloflash error '6400'

### ISSUE THREAD

**Issue by diecasfranco** [HRGV/phyloFlash#116]
Hi all,
I had this error running one metagenomic dataset.

[19:25:10] running subcommand:
	   /mnt/matrix/symbio/software/phyloFlash/phyloFlash_plotscript_svg.pl
	   -tree RANSCY.SSU.collection.fasta.tree -assemcov
	   RANSCY.phyloFlash.extractedSSUclassifications.csv -treefasta
	   RANSCY.SSU.collection.fasta -unassemcount -400
	   >RANSCY.plotscript.out 2>&1
[19:25:10] FATAL: Tool execution failed!.
	   Error was 'Inappropriate ioctl for device' and return code
	   '6400'
	   Aborting.

With other samples works fine but with this always appear the error.

Thanks

**Comment by kbseah** [comment]
Hello @diecasfranco ,
Could you post the contents of the log file `RANSCY.plotscript.out`? Also check whether the files RANSCY.SSU.collection.fasta or RANSCY.phyloFlash.extractedSSUclassifications.csv are empty: I suspect that might be the problem, given that the error only occurs with this one sample.
Best regards,
Brandon
