### ISSUE TITLE
Error while comparing samples with phyloFlash_compare.pl

### ISSUE THREAD

**Issue by mars188** [HRGV/phyloFlash#131]
Hello, 

I generated SSU rRNA abundance files from 3 samples after running `phyloFlash.pl` with appropriate options. 

After that I tried to compare these three samples with the following command:

`phyloFlash_compare.pl --csv CBM.phyloFlash.NTUabundance.csv,EM1.phyloFlash.NTUabundance.csv,EM2.phyloFlash.NTUabundance.csv --task heatmap,barplot --outfmt png` 

The run encountered the following error. 

Use of uninitialized value $count in addition (+) at /scratch/gencore/conda3/envs/pf/bin/phyloFlash_compare.pl line 833.
[16:01:47] Plotting barplot using script:
           /scratch/gencore/conda3/envs/pf/bin/phyloFlash_barplot.R
[16:01:47] NTU abundance by sample table written to temporary file:
           phyloFlash_compare_x3CGMk/qs2FRsciqw
[16:01:47] Plotting barplot: Rscript
           /scratch/gencore/conda3/envs/pf/bin/phyloFlash_barplot.R -f
           phyloFlash_compare_x3CGMk/qs2FRsciqw -t 5 -o
           test.phyloFlash_compare.barplot.png -p Set3
Warning message:
Removed 1818 rows containing missing values (position_stack).
null device
          1
[16:01:49] Barplot written to file: test.phyloFlash_compare.barplot.png
[16:01:49] Plotting heatmap using script:
           /scratch/gencore/conda3/envs/pf/bin/phyloFlash_heatmap.R
[16:01:49] Writing tables for refactored taxonomic abundances to folder
           phyloFlash_compare_x3CGMk/refactor
[16:01:49] Plotting heatmap:
           /scratch/gencore/conda3/envs/pf/bin/phyloFlash_heatmap.R -o
           test.phyloFlash_compare.heatmap.png --cluster-samples=ward.D
           --cluster-taxa=ward.D --min-ntu-count=50
           phyloFlash_compare_x3CGMk/refactor/*.csv
Loading required package: optparse
Selected phyloFlash libraries:
phyloFlash_compare_x3CGMk/refactor/CBM
phyloFlash_compare_x3CGMk/refactor/EM1
phyloFlash_compare_x3CGMk/refactor/EM2

Loading CSV files...
Splitting data according to regex  Eukaryota
A total of 1627 taxa were observed. Merging taxa with < 50 observations into " Other ".
Removed taxa with < 50 observations. 1 taxa left.
A total of 70 taxa were observed. Merging taxa with < 50 observations into " Other ".
Removed taxa with < 50 observations. 1 taxa left.
Rescaling counts to percentages
Clustering...
[1] "3 of 3"
Found 2 taxa and 3 samples.
Creating plot...
Error in g_get(x, "guide-box")$grobs[[1]] : subscript out of bounds
Calls: pF_main ... plot.phyloFlash -> lapply -> FUN -> g_get -> is.ggplot
Execution halted
[16:01:51] Heatmap written to file: test.phyloFlash_compare.heatmap.png
[16:01:51] Thank you for using phyloFlash_compare.pl

As a result, I get two output files:
1. Rplots.pdf
2. test.phyloFlash_compare.barplot.png

Both are empty and contain nothing. Please help me to solve this issue. Thanks!

**Comment by mars188** [comment]
I was able to make it work by using --zip option and running the `phyloFlash_compare.pl` in the same directory where input files are. Now I can generate barplot and heatmaps. 
Thanks!

**Comment by kbseah** [comment]
thanks for following up, and I'm glad you managed to resolve this in the end.
