### ISSUE TITLE
Setting -clusterid to 99 but clustering is still performed at default 97%

### ISSUE THREAD

**Issue by kjvilardi** [HRGV/phyloFlash#134]
I would like set the identity threshold for clustering with vsearch to 99%. However, when I set -clusterid to 99 clustering in the log file says:
clustering DB matches at 97%
running subcommand:
	   /home/vilardi.k/.conda/envs/pf/bin/vsearch	--cluster_fast
	   Filtered_W0_AAGGACCA-AGGAACAC_L00M_LIB.all.final.phyloFlash.dbhits.fa
	   -id 0.97 -centroids
	   Filtered_W0_AAGGACCA-AGGAACAC_L00M_LIB.all.dbhits.NR97.fa

This is my command line:
phyloFlash.pl -lib ${i}_LIB -dbhome /scratch/vilardi.k/phyloflash/138.1 -read1 /scratch/vilardi.k/katiefiles/clean_reads2/all_fq/${i}.clean.R1.fq -read2 /scratch/vilardi.k/katiefiles/clean_reads2/all_fq/${i}.clean.R2.fq -clusterid 99

Do I need to set another parameter to get vsearch to actually cluster at 99%?

**Comment by kbseah** [comment]
Thanks for reporting this, sorry that we didn't catch this issue until now. Bug fix will be implemented in the next release

**Comment by kjvilardi** [comment]
Thank you!
