### ISSUE TITLE
Problem with database when running with -sortmerna

### ISSUE THREAD

**Issue by haitaowang1** [HRGV/phyloFlash#140]
I was running my command: phyloFlash.pl -lib S250 -read1 S250_cat_R1.fastq.gz -read2 S250_cat_R2.fastq.gz -almosteverything -sortmerna -readlength 150

Then I got an error massage: Broken dbhome directory /mnt/Data/haitao/wetscapes_metatrans/138.1: missing file "/mnt/Data/haitao/wetscapes_metatrans/138.1/SILVA_SSU.noLSU.masked.trimmed.NR96.fixed.bursttrie_0.dat"

But I got no error massage when running without '-sortmerna' option.

I don't know what caused this problem. Is this file specifically needed for sortmerna? If yes, how should I get that file. The database was constructed with the standard command: phyloFlash_makedb.pl --remote

I hope someone can help with my issue. Thanks!

Haitao

**Comment by kbseah** [comment]
hello @haitaowang1 , sorry for the late response. Could you run `phyloFlash_makedb.pl` with the additional option `--sortmerna`? phyloFlash uses bbmap to find SSU rRNA-containing reads by default, so the makedb script does not build the SortMeRNA database unless you ask it to. You don't have to download the SILVA database again, but you will need to specify the path with the option `--silva_file /path/to/SILVA_[Release]_SSURef_NR99_tax_silva_trunc.fasta.gz` (replace `/path/to` and `[Release]` with the actual path to the file, and `--univec_file /path/to/Univec`, which should also have been downloaded automatically the last time.
