### ISSUE TITLE
FASTA of unassembled hits

### ISSUE THREAD

**Issue by eolesin** [HRGV/phyloFlash#141]
Why does the output for phyloFlash not provide FASTAs of all the hit reads it is assigning? I get some rare types that I guess don't assemble into a full SSU but I cannot go back and verify them because I cannot fetch the sequence. What am I missing?

**Comment by kbseah** [comment]
Hello @eolesin ,sorry for the late response. The reads containing SSU rRNA sequences are reported in Fastq format; the file names should be of the format `LIBNAME.INPUT_R1.SSU.1.fq` and `LIBNAME.INPUT_R2.SSU.2.fq` where `LIBNAME` is the library name option supplied to phyloFlash with the `-lib` switch, and `INPUT_R1` and `INPUT_R2` are the filenames of the input reads. There should also be a SAM file with the mappings (filename suffix `SSU.sam`) which should contain the information of which reference sequences (and hence taxon strings) the reads map to in the SILVA database.

If you ran phyloFlash with the `-zip`, `-everything` or `-almosteverything` options, these files will be found in the `LIBNAME.phyloFlash.tar.gz` archive.

**Comment by eolesin** [comment]
OK, thank you for the reply. There it is, mystery solved!
