### ISSUE TITLE
SPAdes memory limit

### ISSUE THREAD

**Issue by aleixop** [HRGV/phyloFlash#150]
Hi, thanks for this great tool! Is there a way to increase the 20GB memory limit (`-m 20`) in the SPAdes step? I have 120GB of RAM available but jobs keep crashing due to this limit. Thanks!

**Comment by kbseah** [comment]
At the moment we didn't implement a way to change this from the phyloFlash command line, but you can manually edit the `phyloFlash.pl` script at line 1585 (I think you've already found it) to a higher value. That's the only place the parameter appears, if i remember correctly

**Comment by aleixop** [comment]
Okay, thanks a lot!
