### ISSUE TITLE
new problem installing phyloflash

### ISSUE THREAD

**Issue by pacificasommers** [HRGV/phyloFlash#153]
Hi, I am having an issue installing phyloflash using the recommended approach in conda. 

When I used the recommended approach (including from the previous installation issue) of creating an environment simultaneous with installing phyloflash (with or without sortmeRNA at the same time), `conda create -n pf sortmerna=2.1b phyloflash`, conda just hangs in solving the environment, even when I have set channel priority to strict. (I get the same behavior when they're set to flexible, for what it's worth.)

When I instead tried first creating an environment and then installing just conda using `conda install -c bioconda/label/cf201901 phyloflash` again with channel priority set to strict, I at least got the environment to solve, but the installation failed due to finding conflicts, but after searching for what they were, reporting only: 
"UnsatisfiableError:
Note that strict channel priority may have removed packages required for satisfiability."

It doesn't tell me _what_ packages may have been missing for satisfiability, so I am unable to diagnose if there is something else I can add or change? My searching online to resolve this as a broader issue hasn't yielded any help yet. 

Repeating this attempt to install while already in the environment but with channels set to flexible leads again to conda hanging in solving the environment. 

Any ideas on how to proceed? 

Details on my lab server and conda environment:

**System:** Ubuntu 16.04.7 LTS
**Conda version:** conda 4.10.0
**Python version:** 2.7.12

**My conda config:**
`conda config --show-sources`
==> /home/pacifica/.condarc <==
auto_activate_base: False
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults

**My conda environment:**
`conda info`
     active environment : pf
    active env location : /home/pacifica/.conda/envs/pf
            shell level : 1
       user config file : /home/pacifica/.condarc
 populated config files : /home/pacifica/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.23=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /ResearchSoftware/miniconda3  (read only)
      conda av data dir : /ResearchSoftware/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /ResearchSoftware/miniconda3/pkgs
                          /home/pacifica/.conda/pkgs
       envs directories : /home/pacifica/.conda/envs
                          /ResearchSoftware/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.10.0 requests/2.24.0 CPython/3.8.5 Linux/4.4.0-210-generic ubuntu/16.04.7 glibc/2.23
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False

**Comment by kbseah** [comment]
I'm sorry to hear about this issue, it appears to be a problem with Conda. 

It may help to try using Mamba instead (drop in substitute for Conda): https://mamba.readthedocs.io/en/latest/

**Comment by pacificasommers** [comment]
I had not heard of Mamba before - thanks for the suggestion! I got PhyloFlash installed now!
