### ISSUE TITLE
problems in installing phyloflash and sortmerna

### ISSUE THREAD

**Issue by GeonhoCho** [HRGV/phyloFlash#154]
Hello,

i created a conda environment and installed phyloflash and sortmerna with the following command.

conda create --prefix ./pf -c bioconda —strict-channel-priority phyloflash sortmerna=2.1b

but ended up with the following error message.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libstdcxx-ng conflicts for:
sortmerna=2.1b -> libgcc -> libstdcxx-ng[version='>=7.2.0']
phyloflash -> bedtools -> libstdcxx-ng[version='7.2.0.*|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
sortmerna=2.1b -> libstdcxx-ng[version='>=4.9|>=7.3.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - sortmerna=2.1b -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

Note that strict channel priority may have removed packages required for satisfiability.

any comments are welcome.

**Comment by kbseah** [comment]
Please try using `mamba` instead. See instructions here: https://mamba.readthedocs.io/en/latest/

It is a dropin substitute for conda, and implements a much better environment solver. When I tested your command I got the same error with conda but mamba (v0.1.2) was able to solve the environment.

**Comment by GeonhoCho** [comment]
> Please try using `mamba` instead. See instructions here: https://mamba.readthedocs.io/en/latest/
> 
> It is a dropin substitute for conda, and implements a much better environment solver. When I tested your command I got the same error with conda but mamba (v0.1.2) was able to solve the environment.

It doesn't work, thanks.

**Comment by kbseah** [comment]
Could you please supply the mamba command line you tried and the error message, as well as the output of `conda --version`, and the operating system that you are using?
