### ISSUE TITLE
Conda issue 

### ISSUE THREAD

**Issue by Unaimend** [HRGV/phyloFlash#179]
Hi phyloflash team there is an issue with your dependencies. After following your instructions on adding the channels and the strictness for conda. The command

```
 mamba install -c bioconda phyloflash
```
leads to
![image](https://user-images.githubusercontent.com/7808379/233958599-dbe761b5-14c4-4415-980a-3fc026b852db.png)

**Comment by kbseah** [comment]
Thanks for the report. 

After running some tests it appears that the environment resolution fails if the `defaults` channel is not included:
 * I was able to reproduce error with Mambaforge 
 * Build tests by Bioconda work with the current recipe
 * 

Could you try running this again

**Comment by kbseah** [comment]
Updated Bioconda recipe for phyloflash version 3.4.2 build hdfd78af_1 works without defaults channel. Tested the following command: `mamba create -p ./phyloflash-test -c bioconda phyloflash` on Linux and successfully created environment.

**Comment by Unaimend** [comment]
Worked for me as well
