### ISSUE TITLE
SPAdes crashes when `CPUs` not specified

### ISSUE THREAD

**Issue by kbseah** [HRGV/phyloFlash#37]
When `CPUs` option not set, phyloFlash defaults to all available processors, which causes SPAdes to crash because of memory settings. 

Change default CPUs to some lower number?

**Comment by aassie** [comment]
Spades crashes when too much CPUs are allocated. If you have 1gig of memory it divides the available memory equally between CPUs. I have 20, it make spades trying to run in parallel with 500 mo per thread and it goes out of memory quite quickly.

I go around that problem with setting the CPU number to max 10 but maybe there is a way around this with adjusting the memory options of SPAdes?

**Comment by kbseah** [comment]
There is a `-m` option for SPAdes which sets memory in Gb, and that's probably what's happening because it's set to 20 by phyloFlash, and doesn't change when the number of threads goes up.

**Comment by HRGV** [comment]
fixed
