### ISSUE TITLE
cannot produce heatmap because must have n >= 2 objects to cluster

### ISSUE THREAD

**Issue by jzrapp** [HRGV/phyloFlash#42]
Dear @kbseah,

I tried to produce a heatmap as described in your manual. It seems that I have not enough objects to cluster. In your troubleshooting you say that this may happen if there is only one taxon.. but I know that there are several. Archaea, Bacteria and Eukaryotes. What did I do wrong? (using the latest phyloflash version)

Thanks already!

jrapp@aphros:/scratch2/jrapp/HG_metagenomes_assembly/phyloflash/csv$ phyloFlash_heatmap.R -d -o heatmap.pdf *.csv
Loading required package: optparse
Selected phyloFlash libraries: 
HGI_qc HGIV_qc HGIX_qc HGVI_qc 

Loading CSV files... 
Splitting data according to regex  Eukaryota 
A total of 177 taxa were observed. Merging taxa with < 50 observations into " Other ". 
Removed taxa with < 50 observations. 12 taxa left. 
A total of 9 taxa were observed. Merging taxa with < 50 observations into " Other ". 
Removed taxa with < 50 observations. 1 taxa left. 
Rescaling counts to percentages 
Clustering... 
The "ward" method has been renamed to "ward.D"; note new "ward.D2"
The "ward" method has been renamed to "ward.D"; note new "ward.D2"
The "ward" method has been renamed to "ward.D"; note new "ward.D2"
Error in hclust(dist(mat), method) : must have n >= 2 objects to cluster
Calls: pF_main ... cluster -> lapply -> FUN -> as.dendrogram -> hclust
=============================================================================
 ####  DEBUG Information -- please include with bug reports #### 
=============================================================================
 Encountered error: 
--------------------
Error in hclust(dist(mat), method) : must have n >= 2 objects to cluster
Calls: pF_main ... cluster -> lapply -> FUN -> as.dendrogram -> hclust

 Session Info: 
---------------
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      methods   stats     graphics  grDevices utils     datasets 
[8] base     

other attached packages:
[1] gtable_0.2.0    ggdendro_0.1-20 reshape2_1.4.2  ggplot2_2.2.1  
[5] optparse_1.4.4 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11     MASS_7.3-47      plyr_1.8.4       magrittr_1.5    
 [5] scales_0.4.1     rlang_0.1.1      stringi_1.1.5    lazyeval_0.2.0  
 [9] getopt_1.20.0    tools_3.2.2      stringr_1.2.0    munsell_0.4.3   
[13] colorspace_1.3-2 tibble_1.3.3    
-----------------------------------------------------------------------------
 Call trace: 
-------------
  1: pF_main()
  2: cluster(pf, method = conf$options$"hclust-method")
  3: lapply(pf$data, mkdendro)
  4: FUN(X[[i]], ...)
  5: as.dendrogram(hclust(dist(mat), method))
  6: hclust(dist(mat), method)
  7: stop("must have n >= 2 objects to cluster")
=============================================================================

**Comment by kbseah** [comment]
How many samples are you comparing? Could you send me the .csv files to troubleshoot? Thanks

**Comment by jzrapp** [comment]
four samples. I send the csv files to your mpi address!

**Comment by kbseah** [comment]
Second issue appeared to be from attempting to run R script on cluster. 
Resolved by email. 
@HRGV please close this issue
