### ISSUE TITLE
phyloFlash_plotscript.R not running 

### ISSUE THREAD

**Issue by kbseah** [HRGV/phyloFlash#5]
Hi guys,

I just tried using v 2.0 b2, and everything works fine until generation of the output histogram. I get the error message: 

`Couldn't launch [/data/db/phyloFlash-2.0-beta2/phyloFlash_plotscript.R --args 1418C.SSU.collection.fasta.tree 1418C.inserthistogram  >tmp.1418C.plotscript.out 2>&1]: Inappropriate ioctl for device/32512 at /data/db/phyloFlash-2.0-beta2/PhyloFlash.pm line 161.`

When I look in the file `tmp.1418C.plotscript.out` I see the following message:

`sh: 1: /data/db/phyloFlash-2.0-beta2/phyloFlash_plotscript.R: not found`

However, the R file is present in that directory. The regular text toutput and CSV results are generated, but not the HTML file. 

My command line was: 
`/data/db/phyloFlash-2.0-beta2/phyloFlash.pl -lib 1418C -read1 /data/kentrophoros_illumina/1418/1418_C_run212_GGACCCAT_L001_R1_001_f.fastq.gz -read2 /data/kentrophoros_illumina/1418/1418_C_run212_GGACCCAT_L001_R2_001_f.fastq.gz -CPUs 8 -html -csv`

Thanks,
Brandon

**Comment by HRGV** [comment]
I changed the #! in all *.R files from #!/usr/bin/Rscript to #!/usr/bin/env Rscript

This fixes the problem for most users...
