### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ishengtsai** [HRGV/phyloFlash#8]
Hi ,

I tried to install phyloFlash but encountered the following problem at the ./phyloFlash_makedb.pl stage. Please see the output below. It would be great if you can tell me where the problem is. FYI, I am trying to install under Mac. 

Best,
Jason

[15:33:29] masking low entropy regions in SSU RefNR
[15:33:29] executing [/Users/ishengtsai/bin/bbmap/bbmask.sh   overwrite=t -Xmx4g in=./119//SILVA_SSU.noLSU.fasta out=./119//SILVA_SSU.noLSU.masked.fasta minkr=4 maxkr=8 mr=t minlen=20 minke=4 maxke=8 fastawrap=0 ]
java -ea -Xmx4g -cp /Users/ishengtsai/bin/bbmap/current/ jgi.BBMask overwrite=t -Xmx4g in=./119//SILVA_SSU.noLSU.fasta out=./119//SILVA_SSU.noLSU.masked.fasta minkr=4 maxkr=8 mr=t minlen=20 minke=4 maxke=8 fastawrap=0
Executing jgi.BBMask [overwrite=t, -Xmx4g, in=./119//SILVA_SSU.noLSU.fasta, out=./119//SILVA_SSU.noLSU.masked.fasta, minkr=4, maxkr=8, mr=t, minlen=20, minke=4, maxke=8, fastawrap=0]

Loading input
Loading Time:                 	3.821 seconds.

Masking repeats (to disable, set 'mr=f')
Repeat Masking Time:          	22.440 seconds.
Ref Bases:                 769519778 	34.29m bases/sec
Repeat Bases Masked:            4766

Masking low-entropy (to disable, set 'mle=f')
Low Complexity Masking Time:  	123.443 seconds.
Ref Bases:                 769519778 	6.23m bases/sec
Low Complexity Bases:          10424

Converting masked bases to N
Done Masking
Conversion Time:              	1.166 seconds.

Writing output
Writing Time:                 	2.834 seconds.

Total Bases Masked:            15190/769519778	0.002%
Total Time:                   	153.752 seconds.
[15:36:03] removing UniVec contamination in SSU RefNR
[15:36:03] executing [/Users/ishengtsai/bin/bbmap/bbduk.sh ref=UniVec fastawrap=0 ktrim=r ow=t minlength=800 mink=11 hdist=1 in=./119//SILVA_SSU.noLSU.masked.fasta out=./119//SILVA_SSU.noLSU.masked.trimmed.fasta stats=./119//SILVA_SSU.noLSU.masked.trimmed.fasta.UniVec_contamination_stats.txt]
/Users/ishengtsai/bin/bbmap//calcmem.sh: line 111: [: unlimited: integer expression expected
java -Djava.library.path=/Users/ishengtsai/bin/bbmap/jni/ -ea -Xmx-205m -Xms-205m -cp /Users/ishengtsai/bin/bbmap/current/ jgi.BBDukF ref=UniVec fastawrap=0 ktrim=r ow=t minlength=800 mink=11 hdist=1 in=./119//SILVA_SSU.noLSU.masked.fasta out=./119//SILVA_SSU.noLSU.masked.trimmed.fasta stats=./119//SILVA_SSU.noLSU.masked.trimmed.fasta.UniVec_contamination_stats.txt
Invalid maximum heap size: -Xmx-205m
Could not create the Java virtual machine.
Couldn't launch [/Users/ishengtsai/bin/bbmap/bbduk.sh ref=UniVec fastawrap=0 ktrim=r ow=t minlength=800 mink=11 hdist=1 in=./119//SILVA_SSU.noLSU.masked.fasta out=./119//SILVA_SSU.noLSU.masked.trimmed.fasta stats=./119//SILVA_SSU.noLSU.masked.trimmed.fasta.UniVec_contamination_stats.txt]: /256 at /Users/ishengtsai/bin/phyloFlash/PhyloFlash.pm line 212.

**Comment by HRGV** [comment]
Hi Jason
Invalid maximum heap size: -Xmx-205m is indicating that the automatic memory detection of bbduk failed. I have updated the script and bbduk now is called with 4Gb of heap size.
Thanks for notifying us
Harald
