### ISSUE TITLE
change taxlevel display

### ISSUE THREAD

**Issue by jzrapp** [HRGV/phyloFlash#89]
Hi @kbseah 

Do I have to re-run the analysis if I want to display results at a different taxlevel? Or is there a trick to just restart the final steps of result-compilation? 

Thanks :)
Josi

**Comment by jzrapp** [comment]
Oh, I just saw that I can also specify taxlevel in phyloFlash_compare.pl. So can I use this to display and compare results on taxlevel 6, even if I ran phyloFlash.pl on taxlevel 4?

**Comment by kbseah** [comment]
Hello Josi,

Sorry for taking a while to reply. If you have been using phyloFlash v3 onwards you should be able to specify a lower taxlevel for comparison without re-running the job, even if phyloFlash.pl was originally run on a higher taxlevel. 

You have a few options, depending on how you originally ran `phyloFlash.pl`:

Among the phyloFlash output files, the full NTU taxon strings (not truncated) are written to a file `LIBNAME.phyloFlash.NTUfull_abundance.csv` where LIBNAME is the output prefix given to the `-lib` option of phyloFlash. You should pass these CSV files to `phyloFlash_compare.pl` with the `-csv` option.

If phyloFlash was run with the `-zip` option (recommended), then you should have separate `.tar.gz` files for each phyloFlash job. You can then use the `phyloFlash_compare.pl --allzip` option to process all the phyloFlash .tar.gz archives in the current folder, without separately unpacking the NTU abundance files from each archive. 

If you ran an earlier version of phyloFlash that did not produce the `.phyloFlash.NTUfull_abundance.csv` files, you can use the `--use_SAM` option of `phyloFlash_compare.pl` to recompute the NTU abundances directly from the SAM files output by BBmap during the initial mapping stage. 

Sorry that it is a bit convoluted. I was aiming to preserve older functionality when adding new features, in order not to break peoples' existing workflows with older phyloFlash versions, but these means that some recommended options are not activated by default.

Do let me know if it worked for you!

Cheers,
Brandon
