### ISSUE TITLE
phyloFlash.pl failed at bedtools stage

### ISSUE THREAD

**Issue by ishengtsai** [HRGV/phyloFlash#9]
Hi again,

I tried to execute phyloFlash but without success. Do you have an email address? I am keen to use it and get it working :)

Best Wishes,
Jason

 ./phyloFlash.pl -lib 119 -read1 outpear.assembled.fastq -CPUs 1

[10:56:58] getting 16S phylotypes and their coverages...
[10:56:58] executing [/Users/ishengtsai/bin/phyloFlash/barrnap-HGV/bin/barrnap_HGV --kingdom bac --gene ssu --threads 1 --evalue 1e-200 --reject 0.6 119.spades/scaffolds.fasta >119.scaffolds.bac.gff 2>119.barrnap.out]
[10:57:01] executing [/Users/ishengtsai/bin/phyloFlash/barrnap-HGV/bin/barrnap_HGV --kingdom arch --gene ssu --threads 1 --evalue 1e-200 --reject 0.6 119.spades/scaffolds.fasta >119.scaffolds.arch.gff 2>119.barrnap.out]
[10:57:03] executing [/Users/ishengtsai/bin/phyloFlash/barrnap-HGV/bin/barrnap_HGV --kingdom euk --gene ssu --threads 1 --evalue 1e-200 --reject 0.6 119.spades/scaffolds.fasta >119.scaffolds.euk.gff 2>119.barrnap.out]
[10:57:06] executing [/Users/ishengtsai/bin/bedtools-2.17.0/bin/fastaFromBed   -fi 119.spades/scaffolds.fasta -bed tmp.119.scaffolds.final.gff -fo 119.spades_rRNAs.final.fasta -s -name >tmp.119.fastaFromBed.out 2>&1]
Couldn't launch [/Users/ishengtsai/bin/bedtools-2.17.0/bin/fastaFromBed   -fi 119.spades/scaffolds.fasta -bed tmp.119.scaffolds.final.gff -fo 119.spades_rRNAs.final.fasta -s -name >tmp.119.fastaFromBed.out 2>&1]: No such file or directory/256 at /Users/ishengtsai/bin/phyloFlash/PhyloFlash.pm line 212.

**Comment by epruesse** [comment]
Could you try running the command separately, and paste the output here? I.e. go into the directory in which you ran phyloFlash and execute this line:
```
/Users/ishengtsai/bin/bedtools-2.17.0/bin/fastaFromBed -fi 119.spades/scaffolds.fasta -bed tmp.119.scaffolds.final.gff -fo 119.spades_rRNAs.final.fasta -s -name
```

**Comment by ishengtsai** [comment]
/Users/ishengtsai/bin/bedtools-2.17.0/bin/fastaFromBed -fi
119.spades/scaffolds.fasta -bed tmp.119.scaffolds.final.gff -fo
119.spades_rRNAs.final.fasta -s -name
Error: The requested bed file (tmp.119.scaffolds.final.gff) could not be
opened. Exiting!

On 24 March 2015 at 12:27, Elmar Pruesse <notifications@github.com> wrote:

> Could you try running the command separately, and paste the output here?
> I.e. go into the directory in which you ran phyloFlash and execute this
> line:
>
> /Users/ishengtsai/bin/bedtools-2.17.0/bin/fastaFromBed -fi 119.spades/scaffolds.fasta -bed tmp.119.scaffolds.final.gff -fo 119.spades_rRNAs.final.fasta -s -name
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HRGV/phyloFlash/issues/9#issuecomment-85334690>.
>



-- 
Yours,

**Comment by epruesse** [comment]
So there is no final gff. Perhaps spades was unable to assemble any SSUs from your reads. 

What does 
```
wc -l 119.scaffolds*
```
say?

**Comment by ishengtsai** [comment]
wc -l 119.scaffolds*
       1 119.scaffolds.arch.gff
       1 119.scaffolds.bac.gff
       1 119.scaffolds.euk.gff
       3 total

On 24 March 2015 at 13:25, Elmar Pruesse <notifications@github.com> wrote:

> So there is no final gff. Perhaps spades was unable to assemble any SSUs
> from your reads.
>
> What does
>
> wc -l 119.scaffolds*
>
> say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HRGV/phyloFlash/issues/9#issuecomment-85346359>.
>



-- 
Yours,

**Comment by epruesse** [comment]
Ok, so barrnap didn't find any SSUs in the assemblies. I'll add a check against that. For now, try running phyloFlash with "-skip_spades"

**Comment by ishengtsai** [comment]
It worked! Thanks. I was wondering if the OTUs can be used in qiime or? What softwares would you recommend to visualise the OTUs based on your output?

Best,
Jason

**Comment by HRGV** [comment]
Hi Jason, looking at your first post I saw that you were assembling your reads using pear. That is not necessary, you can input raw data forward and reverse reads, and phyloFlash will infer the insert size from that and optimize the emirge settings.
Could it be you are dealing with amplicon data, and not shotgun metagenomic reads? That would explain the missing assemblies.
