### ISSUE TITLE
phyloFlash aborts upon running subcommand mafft 

### ISSUE THREAD

**Issue by jemo974** [HRGV/phyloFlash#90]
Hi,
When running phyloFlash on PE 150 reads, the script aborts at the subcommand mafft. 
Mafft can be found in the phyloFlash environment. 
Do you know what might be the problem? 

phyloFlash.pl -lib OK1 -read1 SRR1971621_1.cleaned.fq.gz -read2 SRR1971621_2.cleaned.fq.gz -CPUs 16 -readlength 150

This is phyloFlash v3.3b1

[08:58:25] Using dbhome '/home/micro/132'
[08:58:25] working on library OK1
[08:58:25] Forward reads SRR1971621_1.cleaned.fq.gz
[08:58:25] Reverse reads SRR1971621_2.cleaned.fq.gz
[08:58:25] Current operating system linux
[08:58:25] Checking for required tools.
[08:58:25] Using spades found at
	   "/home/micro/tools/anaconda3/bin/spades.py".
[08:58:25] Using bbmap found at
	   "/home/micro/tools/anaconda3/bin/bbmap.sh".
[08:58:25] Using cat found at
	   "/home/micro/tools/anaconda3/bin/cat".
[08:58:25] Using sed found at "/bin/sed".
[08:58:25] Using vsearch found at
	   "/home/micro/tools/anaconda3/bin/vsearch".
[08:58:25] Using barrnap found at
	   "/nfs1/tools/anaconda3/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV".
[08:58:25] Using reformat found at
	   "/home/micro/tools/anaconda3/bin/reformat.sh".
[08:58:25] Using awk found at "/bin/awk".
[08:58:25] Using plotscript_SVG found at
	   "/nfs1/tools/anaconda3/lib/phyloFlash/phyloFlash_plotscript_svg.pl".
[08:58:25] Using nhmmer found at
	   "/nfs1/tools/anaconda3/lib/phyloFlash/barrnap-HGV/binaries/linux/nhmmer".
[08:58:25] Using mafft found at
	   "/home/micro/tools/anaconda3/bin/mafft".
[08:58:25] Using grep found at "/bin/grep".
[08:58:25] Using fastaFromBed found at
	   "/home/micro/tools/anaconda3/bin/fastaFromBed".
[08:58:25] All required tools found.
[08:58:25] filtering reads with SSU db using minimum identity of 70%
[08:58:25] running subcommand:
	   /home/micro/tools/anaconda3/bin/bbmap.sh
	   fast=t minidentity=0.7 -Xmx20g reads=-1 threads=16 po=f
	   outputunmapped=f path=/home/micro/132 out=OK1.bbmap.sam
	   outm=OK1.SRR1971621_1.cleaned.fq.gz.SSU.1.fq noheader=t
	   ambiguous=all build=1 in=SRR1971621_1.cleaned.fq.gz
	   bhist=OK1.basecompositionhistogram ihist=OK1.inserthistogram
	   idhist=OK1.idhistogram scafstats=OK1.hitstats overwrite=t
	   outm2=OK1.SRR1971621_1.cleaned.fq.gz.SSU.2.fq pairlen=1200
	   in2=SRR1971621_2.cleaned.fq.gz 2>OK1.bbmap.out
[09:00:29] done...
[09:00:29] Reading SAM file OK1.bbmap.sam into memory
[09:00:29] Writing fixed SAM file to OK1.SRR1971621_1.cleaned.fq.gz.SSU.sam
[09:00:30] Done
[09:00:30] Total read segments processed: 40789990
[09:00:30] insert size median: 172
[09:00:30] insert size std deviation: 32
[09:00:30] Summarizing taxonomy from mapping hits to SILVA database
[09:00:31] done...
[09:00:31] Forward read segments mapping: 17020
[09:00:31] Reverse read segments mapping: 17045
[09:00:31] Reporting mapping statistics for paired end input
[09:00:31] Total read pairs with at least one segment mapping: 18128
[09:00:31] => both segments mapping to same reference: 14268
[09:00:31] => both segments mapping to different references: 1669
[09:00:31] Read segments where next segment unmapped: 2191
[09:00:31] mapping rate: 0.089%
[09:00:31] creating phylotypes with SPAdes
[09:00:31] kmers for SPAdes are 99,111,127
[09:00:31] running subcommand:
	   /home/micro/tools/anaconda3/bin/spades.py
	   -o OK1.spades -t 16 -m 20 -k 99,111,127 -1
	   OK1.SRR1971621_1.cleaned.fq.gz.SSU.1.fq -2
	   OK1.SRR1971621_1.cleaned.fq.gz.SSU.2.fq >OK1.spades.out 2>&1
[09:01:04] done...
[09:01:04] getting SSU phylotypes and their coverages...
[09:01:04] running subcommand:
	   /nfs1/tools/anaconda3/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
	    --evalue 1e-100 --reject 0.6 --kingdom bac --gene ssu --threads
	   16 OK1.spades/scaffolds.fasta >OK1.scaffolds.bac.gff
	   2>OK1.barrnap.out
[09:01:05] running subcommand:
	   /nfs1/tools/anaconda3/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
	    --evalue 1e-100 --reject 0.6 --kingdom arch --gene ssu
	   --threads 16 OK1.spades/scaffolds.fasta >OK1.scaffolds.arch.gff
	   2>OK1.barrnap.out
[09:01:07] running subcommand:
	   /nfs1/tools/anaconda3/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
	    --evalue 1e-100 --reject 0.6 --kingdom euk --gene ssu --threads
	   16 OK1.spades/scaffolds.fasta >OK1.scaffolds.euk.gff
	   2>OK1.barrnap.out
[09:01:09] running subcommand:
	   /home/micro/tools/anaconda3/bin/fastaFromBed
	   -fi OK1.spades/scaffolds.fasta -bed OK1.scaffolds.final.gff -fo
	   OK1.spades_rRNAs.fastaFromBed.fasta -s -name
	   >OK1.fastaFromBed.out 2>&1
[09:01:09] done...
[09:01:09] mapping extracted SSU reads back on SPAdes SSU sequences
[09:01:09] running subcommand:
	   /home/micro/tools/anaconda3/bin/bbmap.sh
	   fast=t minidentity=0.98 -Xmx20g threads=16 po=f outputunmapped=t
	   ref=OK1.spades_rRNAs.final.fasta nodisk
	   in=OK1.SRR1971621_1.cleaned.fq.gz.SSU.1.fq
	   out=OK1.SRR1971621_1.cleaned.fq.gz.SSU_spades.sam noheader=t
	   overwrite=t in2=OK1.SRR1971621_1.cleaned.fq.gz.SSU.2.fq
	   pairlen=1200 2>OK1.remap_spades.bbmap.out
[09:01:18] done...
[09:01:18] searching for DB matches with vsearch
[09:01:18] running subcommand:
	   /home/micro/tools/anaconda3/bin/cat
	   OK1.spades_rRNAs.final.fasta >OK1.all.final.fasta
[09:01:18] Vsearch v2.5.0+ found, will index database to UDB file
[09:01:18] running subcommand:
	   /home/micro/tools/anaconda3/bin/vsearch
	   -usearch_global OK1.all.final.fasta -id 0.7 -userout
	   OK1.all.vsearch.csv -userfields
	   query+target+id+alnlen+evalue+id3+qs+pairs+gaps+mism+ids
	   -threads 16 --strand plus --notrunclabels -notmatched
	   OK1.all.final.phyloFlash.notmatched.fa -dbmatched
	   OK1.all.final.phyloFlash.dbhits.fa -db
	   /home/micro/132/SILVA_SSU.noLSU.masked.trimmed.udb
	   >OK1.all.vsearch.out 2>&1
[09:01:26] done...
[09:01:26] clustering DB matches at 97%
[09:01:26] running subcommand:
	   /home/micro/tools/anaconda3/bin/vsearch 
	    --cluster_fast OK1.all.final.phyloFlash.dbhits.fa -id 0.97
	   -centroids OK1.all.dbhits.NR97.fa -notrunclabels --threads 16
	   >OK1.clusterdbhits.out 2>&1
[09:01:26] done...
[09:01:26] creating alignment and tree...
[09:01:26] running subcommand:
	   /home/micro/tools/anaconda3/bin/cat
	   OK1.all.dbhits.NR97.fa OK1.spades_rRNAs.final.fasta
	   >OK1.SSU.collection.fasta
[09:01:26] running subcommand:
	   /home/micro/tools/anaconda3/bin/mafft
	   --treeout OK1.SSU.collection.fasta
	   >OK1.SSU.collection.alignment.fasta
	   2>OK1.SSU.collection.alignment.mafftout
[09:01:26] FATAL: Tool execution failed!.
	   Error was '' and return code '256'
	   Aborting.

**Comment by kbseah** [comment]
Hello, thanks for reporting the issue!
Have you managed to use phyloFlash successfully on other data sets before, or is this the first time you're trying it out? 
Could you please run phyloFlash again with the `--keeptmp` option (leaving the other parameters the same) and post the contents of the log file `OK1.SSU.collection.alignment.mafftout` here? That would help us diagnose the problem.

**Comment by jemo974** [comment]
Hi, thank you for the prompt response. It's my first time running phyloFlash. 
Here's the report OK1.SSU.collection.alignment.mafftout:
mktemp: failed to create directory via template '/data/mafft.XXXXXXXXXX': Permission denied
mktemp seems to be obsolete. Re-trying without -t
mkdir: cannot create directory '/data/tmp': Permission denied
mktemp: failed to create directory via template '/data/tmp/mafft.XXXXXXXXXX': No such file or directory
/home/micro/tools/anaconda3/bin/mafft: line 1022: /infile: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1023: /infile: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1024: /infile: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1025: /_addfile: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1026: /_aamtx: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1027: /_subalignmentstable: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1028: /_guidetree: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1029: /_seedtablefile: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1030: /_lara.params: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1031: /pdblist: Permission denied
/home/micro/tools/anaconda3/bin/mafft: line 1032: /ownlist: Permission denied
grep: /infile: No such file or directory
/home/micro/tools/anaconda3/bin/mafft: line 1670: [: -gt: unary operator expected
grep: /infile: No such file or directory
/home/micro/tools/anaconda3/bin/mafft: line 1679: [: -eq: unary operator expected
/home/micro/tools/anaconda3/bin/mafft: line 1686: [: too many arguments
/home/micro/tools/anaconda3/bin/mafft: line 2437: infile: No such file or directory

**Comment by jemo974** [comment]
It's working now. It looks like I needed to set the path of $MAFFT_BINARIES.

**Comment by kbseah** [comment]
Thanks for the report, and for sharing how you resolved it in the end. I've not seen this issue before, so it'll be useful if anyone else encounters something similar!

**Comment by jiee1993** [comment]
I encounter the same problem:
`[21:28:41] running subcommand:
	   miniconda2-new/envs/phyloflash/bin/mafft
	   --treeout S1.SSU.collection.fasta
	   >S1.SSU.collection.alignment.fasta
	   2>S1.SSU.collection.alignment.mafftout
[21:28:41] FATAL: Tool execution failed!.
	   Error was '' and return code '256'
	   Aborting.`

And the `cat S1.SSU.collection.alignment.mafftout` says:
`miniconda2-new/envs/phyloflash/bin/mafft: line 2550: /dev/stderr: Not a directory`

Any solutions to solve the problem?

**Comment by kbseah** [comment]
Hello @jiee1993 , thanks for the report. I saw that you closed the issue. Did you figure out what was the issue in the end?

**Comment by kbseah** [comment]
@jiee1993 apologies I confused this issue with another one, I realize now that you didn't close this issue. 

Could you please post the original command line that you used for phyloFlash, and the full contents of the file `S1.SSU.collection.alignment.mafftout`?

**Comment by jiee1993** [comment]
Thanks for your reply.
The cmd line I use was: `phyloFlash.pl -lib id -read1 final_pure_reads_1.fastq -read2 final_pure_reads_2.fastq -almosteverything -dbhome DB/phyloflash/138/ -CPUs 60 -readlength 150 -taxlevel 6`.
And the full contents of `S1.SSU.collection.alignment.mafftout` is just: `miniconda2-new/envs/phyloflash/bin/mafft: line 2550: /dev/stderr: Not a directory`.
After I remove line 2296 of `phyloFlash.pl` source code, the program finished normally and I get the results. So is there any problem about the result I get in the way?

**Comment by kbseah** [comment]
Hm I've not seen this error before. Does your phyloFlash output report in HTML format also contain a tree? We use Mafft to align the assembled/reconstructed SSU rRNA sequences and produce a rough tree for the report. It should not affect the other outputs from the pipeline. 

Nonetheless it would be good to figure out what is going on. Does the issue recur with other input files? Which version of phyloFlash are you using? What is your OS? Could you please quote the lines that you removed from the source code (or the adjacent lines)? Thanks a lot!

**Comment by jiee1993** [comment]
Yes, HTML report DO have a tree. 
The issue recur with all my input files.
`The phyloFlash is v3.3b1`.
`CentOS release 6.5`.
I modified 
`run_prog("mafft",
             "--treeout ".$outfiles{"ssu_coll_fasta"}{"filename"},
             $outfiles{"ssu_coll_aln_fasta"}{"filename"},
             $outfiles{"ssu_coll_aln_mafftout"}{"filename"});`
to 
`run_prog("mafft",
             "--treeout ".$outfiles{"ssu_coll_fasta"}{"filename"},
             $outfiles{"ssu_coll_aln_fasta"}{"filename"});`

**Comment by kbseah** [comment]
Thanks for the information. What I understand from this is that there is a problem with redirecting the stderr output of Mafft to a log file. Your modification removes the redirect so that the stderr is not piped into a log file.

The closest that I could find online was this post: https://stackoverflow.com/questions/26623626/bash-redirect-to-dev-stdout-not-a-directory

That seems to suggest that it has something to do with the file system. I think that the underlying issue is with Mafft rather than the phyloFlash code, because the stderr redirect for other programs in the pipeline appear to cause no issues. 

Thanks again for identifying this bug, unfortunately I don't think this is something that we can fix at the moment. However I can say that your mod should not have any effect on the output except for throwing away the Mafft error messages.

**Comment by jiee1993** [comment]
@kbseah Ok. Thanks for your affirmation of the correctness of results. And thanks a lot for your wonderful program!
