### ISSUE TITLE
phyloFlash.pl -check_env error

### ISSUE THREAD

**Issue by YiweiNiu** [HRGV/phyloFlash#94]
Hi,

I got the following error message when typing `./phyloFlash.pl -check_env`.

```bash
niuyw@admin:~/software/phyloFlash-pf3.3b1$ ./phyloFlash.pl -check_env
Bareword found where operator expected at /home/niuyw/software/phyloFlash-pf3.3b1/PhyloFlash.pm line 131, near "s/.*\/[^\d]*//r"
syntax error at /home/niuyw/software/phyloFlash-pf3.3b1/PhyloFlash.pm line 131, near "s/.*\/[^\d]*//r"
BEGIN not safe after errors--compilation aborted at /home/niuyw/software/phyloFlash-pf3.3b1/PhyloFlash.pm line 705.
Compilation failed in require at ./phyloFlash.pl line 285.
BEGIN failed--compilation aborted at ./phyloFlash.pl line 285.
```

I am using perl v5.10.1 on a CentOS 6 system. I know little about perl. Any help would be appreciated.

Bests,
Yiwei Niu

**Comment by kbseah** [comment]
Hello Yiwei,

Thanks for getting in touch. The version of perl you're using is quite out of date. The line above will fail with perl versions below 5.13.2. Could you update your perl version and see if it works? 

Alternatively, you can use [Conda](https://conda.io/en/latest/) to manage the dependencies. 

Instructions for installing phyloFlash with Conda are [here](http://hrgv.github.io/phyloFlash/install.html)

Please let us know if there's any further issues with using phyloFlash.

Best regards,
Brandon

**Comment by YiweiNiu** [comment]
Hi Brandon,

Thank you for your reply. 

I re-installed `phyloFlash` using Conda and it worked now.

Bests,
Yiwei Niu
