### ISSUE TITLE
can't create database using phyloFlash_makedb.pl

### ISSUE THREAD

**Issue by sashulkaSh** [HRGV/phyloFlash#98]
hello!
can't create database using phyloFlash_makedb.pl

i run:
phyloFlash_makedb.pl --univec_file /media/kotenko/Elements/DB/UniVec/UniVec --silva_file /media/kotenko/Elements/DB/SILVA_138/SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz --overwrite

out:

[16:46:08] Checking for required tools.
[16:46:08] Using bbduk found at
           "/home/kotenko/anaconda2/envs/pf/bin/bbduk.sh".
[16:46:08] Using bbmask found at
           "/home/kotenko/anaconda2/envs/pf/bin/bbmask.sh".
[16:46:08] Using grep found at "/bin/grep".
[16:46:08] Using barrnapHGV found at
           "/home/kotenko/anaconda2/envs/pf/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV".
[16:46:08] Using bowtiebuild found at
           "/home/kotenko/anaconda2/envs/pf/bin/bowtie-build".
[16:46:08] Using vsearch found at
           "/home/kotenko/anaconda2/envs/pf/bin/vsearch".
[16:46:08] Using bbmap found at
           "/home/kotenko/anaconda2/envs/pf/bin/bbmap.sh".
[16:46:08] All required tools found.

This is phyloFlash_makedb.pl from phyloFlash.pl v3.3b1

[16:46:08] using local copy of univec:
           /media/kotenko/Elements/DB/UniVec/UniVec
[16:46:08] using local copy of Silva SSU RefNR:
           /media/kotenko/Elements/DB/SILVA_138/SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz
[16:46:08] FATAL: Failed to create dir 138/SILVA
           No such file or directory
           Aborting.

what is wrong with this?

when i run:
phyloFlash.pl -dbhome /media/kotenko/Elements/DB/SILVA_138

out:
This is phyloFlash v3.3b1

Broken dbhome directory: missing file "/media/kotenko/Elements/DB/SILVA_138/ref/genome/1/summary.txt"

**Comment by kbseah** [comment]
Thanks for reporting this issue. The issue is a regex that looks for the SILVA database filename and uses it to name the downstream database files. Because the folder name also contains `SILVA_`, the regex messes up. Could you please rename the folder to something else that doesn't start with `SILVA_` and try again?

**Comment by kbseah** [comment]
To do: Use `File::Basename` to handle parsing of DB file paths

**Comment by kbseah** [comment]
@sashulkaSh you should also check out issue #100 which will also be relevant to you. Have submitted a pull request addressing the naming change, will work on the DB file path next

**Comment by sashulkaSh** [comment]
Thanks for your reply and sorry for my delayed reply. I changed the path to the Silva database so that there are no intermediate folders containing part of the file name /media/kotenko/Elements/DB/SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz
(then for some reason folder 138 was created in the folder / media / kotenko / Elements / DB / UniVec)

**Comment by kbseah** [comment]
Hi @sashulkaSh, the `phyloFlash_makedb.pl` script will put all the database files in a single folder named after the SILVA version number (in case people are working with different db versions), in this case it's called `138/`. When you run the `phyloFlash.pl ` script you can specify the db path using the `-dbhome` option. Thanks again for reporting the issue, and do let us know if you encounter other problems!

**Comment by sashulkaSh** [comment]
> Hi @sashulkaSh, the `phyloFlash_makedb.pl` script will put all the database files in a single folder named after the SILVA version number (in case people are working with different db versions), in this case it's called `138/`. When you run the `phyloFlash.pl ` script you can specify the db path using the `-dbhome` option. Thanks again for reporting the issue, and do let us know if you encounter other problems!

thank you!
